source 'https://rubygems.org'

# gem "sinatra"

#gem "pg"
#gem "activerecord"
#gem "sinatra-activerecord"

# gem 'sinatra-contrib'

gem "grape", "~> 0.5.0"
gem "rack-cors", "~> 0.2.8"

gem "mongoid", "~> 3.1.4"
gem "bson_ext", "~> 1.9.1"