source 'https://rubygems.org'

gem 'goliath', "~> 1.0.3"
gem 'grape', "~> 0.5.0"
gem "activerecord", "~> 4.0.0"
gem 'yajl-ruby', "~> 1.1.0"
gem "rack-cors", "~> 0.2.8"

gem 'em-synchrony', "~> 1.0.3"
gem "mysql2", "~> 0.3.11"

gem "pg", "~> 0.15.1"
gem 'em-postgresql-adapter', :git => 'git://github.com/leftbee/em-postgresql-adapter.git'

gem "rspec", "~> 2.14.1"
gem "em-http-request", "~> 1.1.0"
