task :default do
  exec "rake -T"
end

desc "Run Development Server"
task :run_dev do
  # https://github.com/postrank-labs/goliath/wiki/Server
  system "ruby piecemaker.rb --port 9080 \
                             --environment dev \
                             --log log/log.txt \
                             --stdout"
end

desc "Run Production Server"
task :run_prod do
  # https://github.com/postrank-labs/goliath/wiki/Server
  system "ruby piecemaker.rb --port 9080 \
                             --environment prod \
                             --log log/log.txt"
end

desc "run apache ab benchmarking"
task :ab_benchmark do
  # http://httpd.apache.org/docs/2.2/programs/ab.html
  system "ab -c 2 -n 100 http://localhost:9080/v1/users"
end

require 'active_record'

desc "Migrate the database through scripts in db/migrate. Target specific version with VERSION=x"
task :migrate => :environment do
  ActiveRecord::Migrator.migrate('db/migrate', nil )
end

task :environment do
    ActiveRecord::Base.establish_connection(:adapter  => 'em_mysql2',
                                          :database => 'piecemaker2',
                                          :username => 'root',
                                          :password => '',
                                          :host     => 'localhost',
                                          :pool     => 1)
    
  ActiveRecord::Base.logger = Logger.new(File.open('database.log', 'a'))
end


desc "run tests"
task :test do
  system "rspec spec/*"
end