desc "see usage"
task :default do 
  system 'rake -T'
end

desc "start api"
task :start_api do
  system 'node api.js'
end

desc "test routes"
task :test do 
  system './node_modules/.bin/mocha \
    --reporter nyan \
    --timeout 10000 \
    spec/*.js spec/controllers/*.js'
end

desc "debug api (mattes env)"
task :debug_mattes_env do
  system 'nodemon -w . -w ../../node-rest-api/lib/ api.js'
end

desc "generate routes.html|.md"
task :routes do
  routes = []

  # read files in ./controllers
  files = Dir.glob("./controllers/*")
  files.each do |file|
    # read files content
    content = File.read(file)
  
    block = {
      'signature' => '',
      'likes' => '',
      'returns' => '',
      'comments' => '',
      'url_params' => ''
    }
    new_block = false
    content.each_line do |line|

      if new_block
        routes.push block
        # ready for new block
        new_block = false
        block = {}
      end

      if line.start_with? "  '"
        block['signature'] = line.strip[1..-3]

      elsif line.start_with? "  //  likes "
        block['likes'] = line.strip[10, line.length]

      elsif line.start_with? "  //  returns "     
        block['returns'] = line.strip[12, line.length]

      elsif line.start_with? "  // "
        block['comments'] = line.strip[3, line.length]

      elsif line.start_with? "  function($"
        block['url_params'] = line.strip[10, line.length][/[^\)\}]*/]
        if block['url_params'].start_with? ','
          block['url_params'] = block['url_params'][2, block['url_params'].length] 
        end
        new_block = true
      end
    end

  end

  # html file 
  f = File.open('routes.html', 'w')
  f.write '<html><head><style>'
  f.write '@media all { td { border-bottom: 1px solid #666666; } }'
  f.write 'body, td { font-size: 12px; font-family: monospace; }'
  f.write 'tr:nth-child(2n+1) { background-color: #D3E3ED; }'
  f.write 'td, th { padding:3px 5px; text-align: left; }'
  f.write 'tr:hover { background-color: #86E3C7; }'
  f.write 'u { text-decoration: none; }'

  f.write '</style></head><body>'
  f.write '<table>'
  f.write '<thead><tr><th></th><th>Route</th><th>Params <i>(* required)</i></th><th>Returns</th></tr></thead>'

  routes.each do |route|
    f.write "<tr>"
    f.write "<td><input type='checkbox'></td>"
    f.write "<td width='50%'><strong><u>" << route['signature'] << "</u></strong><br>" << route['comments'] << "</td>"
    f.write "<td>" << route['likes']  << "</td>"
    f.write "<td>" << route['returns']  << "</td>"
    f.write "</tr>"
  end
  
  f.write '</table></body></html>'
  f.close
  puts 'open routes.html in your browser'


  # markdown file 
  f = File.open('routes.md', 'w')

  routes.each do |route|
    f.write "__" << route['signature'] << "__\n" 
    f.write " * " << route['comments'] << "\n" 
    f.write " * Likes: ```" << route['likes']  << "```\n"
    f.write " * Returns: ```" << route['returns']  << "```\n"
    f.write "  \n"
  end
  
  f.close
  puts 'open routes.md in your editor'

  # @TODO http://apigee.com/docs/enterprise/content/wadl-reference

end