source "http://rubygems.org"

gem "rack", "~> 1.4.1"
gem "grape", "~> 0.5.0"
gem "json", "~> 1.7.7"
gem "newrelic_rpm", "~> 3.6.5.130"
gem "newrelic-grape", "~> 1.3.1"
gem "rack-cors", "~> 0.2.8"
gem "grape-swagger", "~> 0.6.0"
gem "thin", "~> 1.5.1"

gem "activerecord", "~> 4.0.0", :require => "active_record"
gem "pg", "~> 0.15.1"

group :development do
  gem "rake", "~> 10.1.0"
  gem "guard", "~> 1.6.1"
  gem "guard-bundler", "~> 1.0.0"
  gem "guard-rack", "~> 1.2.2"
  gem "guard-rake", "~> 0.0.9"
end

group :test do
  gem "rspec", "~> 2.14.1"
  gem "rack-test", "~> 0.6.2"
  gem "factory_girl", "~> 4.0"
end

