guard 'bundler' do
  watch('Gemfile')
end

guard 'rack' do
  watch('Gemfile.lock')
  watch(%r{^(config|app|api)/.*})
end

guard 'rake', :task => 'spec' do
  watch(%r{^(config|app|api|spec/api)/.*})
end


