group :default do

  guard 'bundler' do
    watch('Gemfile')
  end

  guard 'rack' do
    watch('Gemfile.lock')
    watch(%r{^(config|app|api)/.*})
  end

  guard 'rake', :task => 'spec' do
    watch(%r{^(config|app|api|spec/api|spec/models)/.*})
  end

end

group :specs do
  guard 'rake', :task => 'spec:now' do
    watch(%r{^(config|app|api|spec/api|spec/models)/.*})
  end
end