desc "see usage"
task :default do 
  system 'rake -T'
end

desc "Run App"
task :run_test_env do
  system "export NODE_ENV=test; node app"
end

desc "Run App with nodemon"
task :nodemon do
  system "export NODE_ENV=test; ./node_modules/.bin/nodemon -w . app.js"
end

desc "Run ab benchmarks"
task :ab_benchmark do
  # http://httpd.apache.org/docs/2.2/programs/ab.html
  system "ab -c 2 -n 50 http://127.0.0.1:9050/users"
end