require 'rubygems'
require 'bundler'

begin
  Bundler.setup(:default, :development, :test)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end

require 'rake'
require 'rspec/core'
require 'rspec/core/rake_task'
require "sequel"

def expand_env_string(env)
  return "development" if env == "dev"
  return "production" if env == "prod"
  return env
end

namespace :spec do

  desc "run tests on change"
  task :onchange do 
    system "guard -g specs"
  end

  desc "run tests"
  RSpec::Core::RakeTask.new(:now) do |spec|
    # do not run integration tests, doesn't work on TravisCI
    # spec.pattern = FileList['spec/api/*_spec.rb', 'spec/models/*_spec.rb']
    spec.pattern = FileList['spec/models/*_spec.rb']
  end  
end



task :default do
  exec "rake -T"
end

namespace :start do
  desc "Start :development environment"
  task :dev do
    system "bundle exec guard -g default"
  end

  desc "Start :production environment"
  task :prod do
    system "RACK_ENV=production rackup"
  end
end


task :environment, [:env] do |cmd, args|
  ENV["RACK_ENV"] = expand_env_string(args[:env]) || "development"
  require "./config/environment"
end

namespace :db do
  desc "Create admin user"
  task :create_admin, :env do |cmd, args|
    env = expand_env_string(args[:env]) || "development"
    Rake::Task['environment'].invoke(env)

    require "Digest"
    DB[:users].insert(
      :name => "Super Admin", 
      :email => "super@example.com",
      :password => Digest::SHA1.hexdigest("Super Admin"),
      :api_access_key => "xadmin",
      :is_admin => true
      )
  end

  desc "Run database migrations"
  task :migrate, :env do |cmd, args|
    env = expand_env_string(args[:env]) || "development"
    Rake::Task['environment'].invoke(env)
 
    require 'sequel/extensions/migration'
    Sequel::Migrator.apply(DB, "db/migrations")
  end
 
  desc "Rollback the database"
  task :rollback, :env do |cmd, args|
    env = expand_env_string(args[:env]) || "development"
    Rake::Task['environment'].invoke(env)
 
    require 'sequel/extensions/migration'
    version = (row = DB[:schema_info].first) ? row[:version] : nil
    Sequel::Migrator.apply(DB, "db/migrations", version - 1)
  end
 
  desc "Nuke the database (drop all tables)"
  task :nuke, :env do |cmd, args|
    env = expand_env_string(args[:env]) || "development"
    Rake::Task['environment'].invoke(env)
    DB.tables.each do |table|
      # @todo: CASCADE equivalent command for DB.drop_table?
      # DB.drop_table(table)
      # DB[table.to_sym].drop(:cascade => true)
      DB.run("DROP TABLE #{table} CASCADE")
    end
  end
 
  desc "Reset the database"
  task :reset, :env do |cmd, args|
    env = expand_env_string(args[:env])
    Rake::Task['db:nuke'].invoke(env)
    Rake::Task['db:migrate'].invoke(env)
  end
end

